### ISSUE TITLE
Add osx arm builds

### ISSUE THREAD

**Issue by giswqs** [conda-forge/torchtext-feedstock#6]
### Comment:

It would be great to add osx arm builds so that torchtext can support Apple M1 chip. I am not sure if this is feasible due to the complexity of torchtext builds. 

I was able to add osx arm builds for [`autogluon.core`](https://github.com/conda-forge/autogluon.core-feedstock/pull/7) by following the [conda-forge instructions](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/) on arm builds. The `torchtext` recipe is a lot more complex than `autogluon.core`, so I am not sure if the same instructions would work.

**Comment by h-vetinari** [comment]
Please open a PR to the pinning repo that adds torchtext to the osx-arm migration. Then we'll have a look how it goes

**Comment by ngam** [comment]
hi @giswqs could you let me know where I could help with the ongoing effort? I read through the issue open at autogluon but I am not sure where to help... there's been a lot of activity on this front!

**Comment by ngam** [comment]
I agree waiting for the migrator is best of these migrations btw. Otherwise, one may waste time chasing deps

**Comment by giswqs** [comment]
@ngam Sorry for that long thread on the autogluon repo. We were trying to publish 15+ dependencies on conda-forge before we can publish autogluon on conda-forge. 

For now, there are two packages we need help with. The first one is ray. It does not support osx & arm64. See this PR that @h-vetinari have been working with. 
https://github.com/conda-forge/ray-packages-feedstock/pull/80

The second one is torchtext. It would be great if we can add support for arm64.

**Comment by ngam** [comment]
Alright, sounds good. I think we will wait for this to go through https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4010 and then follow up here. It's cleaner that way. I will have a look at ray now and see if I can help. I will try to debug with @h-vetinari (I have access to arm64 machines)

**Comment by giswqs** [comment]
Both ray and torchtext are dependencies of autogluon. We are trying to add support for arm64 so that Apple M1/M2 users can use these packages. Let's wait for https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4010 to be merged and see how it goes. 

Another dependency is catboost, which does not support arm64. I opened a PR [here](https://github.com/conda-forge/catboost-feedstock/pull/95), but the ARM build failed. I have not figured it out yet. Any help will be appreciated.

**Comment by h-vetinari** [comment]
The biggest issue by far IMO is building ray for osx _at all_, see [here](https://github.com/conda-forge/ray-packages-feedstock/issues/2). The osx-arm things are usually quite solvable in comparison. On the ray-feedstock we don't have many people able to debug this (there's an open PR), so if you could help there @ngam, that would be splendid 🙃

**Comment by ngam** [comment]
I will start looking. It's been pretty difficult to decipher what's going on with the ray build, but hopefully, I will find more time to tinker soon.

<details>
(Also, not sure where else to tell you this, but I got my new compute resources, though I need some time to navigate the policies etc. and get settled into my no-questions-asked accounts, which now include ppc, but resources will be hard-timed, likely on the order of 10s of thousands of hours per year)
